
after-login-command = []
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 8
inner.vertical =   8
outer.left =       0
outer.bottom =     0
outer.top =        0
outer.right =      0

# 'main' binding mode declaration

[mode.main.binding]

alt-slash = 'layout tiles horizontal vertical'

# Move within Workspace
alt-ctrl-left = 'move left'
alt-ctrl-down = 'move down'
alt-ctrl-up = 'move up'
alt-ctrl-right = 'move right'

# Resizing
alt-ctrl-minus = 'resize smart +100'
alt-ctrl-equal = 'resize smart -100'
alt-ctrl-0 = 'fullscreen'
alt-ctrl-9 = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
alt-ctrl-8 = 'layout tiles horizontal vertical' # Toggle between vertical and horizontal layout


# Switch Workspace
alt-1 = 'workspace âš”ï¸'
alt-2 = 'workspace â˜ ï¸'
alt-3 = 'workspace ğŸ§™ğŸ»â€â™‚ï¸'
alt-4 = 'workspace ğŸ§›ğŸ»â€â™‚ï¸'
alt-5 = 'workspace ğŸ§ğŸ¼â€â™‚ï¸'
alt-6 = 'workspace ğŸ‘»'

# Move application to Workspace
alt-ctrl-1 = ['move-node-to-workspace âš”ï¸', 'workspace âš”ï¸']
alt-ctrl-2 = ['move-node-to-workspace â˜ ï¸', 'workspace â˜ ï¸']
alt-ctrl-3 = ['move-node-to-workspace ğŸ§™ğŸ»â€â™‚ï¸', 'workspace ğŸ§™ğŸ»â€â™‚ï¸']
alt-ctrl-4 = ['move-node-to-workspace ğŸ§›ğŸ»â€â™‚ï¸', 'workspace ğŸ§›ğŸ»â€â™‚ï¸']
alt-ctrl-5 = ['move-node-to-workspace ğŸ§ğŸ¼â€â™‚ï¸', 'workspace ğŸ§ğŸ¼â€â™‚ï¸']
alt-ctrl-6 = ['move-node-to-workspace ğŸ‘»', 'workspace ğŸ‘»']

# alt-tab = 'workspace-back-and-forth'
alt-ctrl-tab = 'move-workspace-to-monitor --wrap-around next'
alt-ctrl-m = 'mode service'

# 'service' binding mode declaration.
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout

alt-ctrl-h = ['join-with left', 'mode main']
alt-ctrl-j = ['join-with down', 'mode main']
alt-ctrl-k = ['join-with up', 'mode main']
alt-ctrl-l = ['join-with right', 'mode main']


# Assign apps to workspaces

[[on-window-detected]]
if.app-id = 'com.vivaldi.Vivaldi'
run = "move-node-to-workspace âš”ï¸"

[[on-window-detected]]
if.app-id = 'com.apple.Music'
run = "move-node-to-workspace â˜ ï¸"

[[on-window-detected]]
if.app-id = 'com.whispersystems.signal-desktop'
run = "move-node-to-workspace â˜ ï¸"

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = "move-node-to-workspace â˜ ï¸"

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = "move-node-to-workspace ğŸ§™ğŸ»â€â™‚ï¸"

[[on-window-detected]]
if.app-id = 'com.figma.Desktop'
run = "move-node-to-workspace ğŸ§›ğŸ»â€â™‚ï¸"

[[on-window-detected]]
if.app-id = 'com.microsoft.Teams'
run = "move-node-to-workspace ğŸ§ğŸ¼â€â™‚ï¸"

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = "move-node-to-workspace ğŸ§ğŸ¼â€â™‚ï¸"

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = "move-node-to-workspace ğŸ‘»"

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = "move-node-to-workspace ğŸ‘»"
